language: c
sudo: false
services:
    - docker
install:
    - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script:
    - bash -ex .travis-docker.sh
env:
    global:
        - OCAML_VERSION=4.04.2
        - DISTRO=debian-stable
        - PINS="rrdd-plugin:. xapi-rrdd-plugin:."
        - PACKAGE=rrdd-plugin
    matrix:
        # We need to pass some Travis environment variables to the container to
        # enable uploading to coveralls and detection of Travis CI.
        # Also, set TESTS to false to avoid running them twice.
        - BASE_REMOTE=git://github.com/xapi-project/xs-opam
        - EXTRA_REMOTES=git://github.com/xapi-project/xs-opam
matrix:
    fast_finish: true
    allow_failures:
        - env: EXTRA_REMOTES=git://github.com/xapi-project/xs-opam
